// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "d5ad64e0d4c696834d733d9e6ae42ad6dd553a19f794c7fc880840bc46023ef6")
