// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datadog/config/config.proto

package pbgo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product int32

const (
	Product_NO_PRODUCT       Product = 0
	Product_LIVE_DEBUGGING   Product = 1
	Product_APPSEC           Product = 2
	Product_RUNTIME_SECURITY Product = 3
	Product_APM_SAMPLING     Product = 4
	Product_TESTING1         Product = 5
	Product_TESTING2         Product = 6
)

var Product_name = map[int32]string{
	0: "NO_PRODUCT",
	1: "LIVE_DEBUGGING",
	2: "APPSEC",
	3: "RUNTIME_SECURITY",
	4: "APM_SAMPLING",
	5: "TESTING1",
	6: "TESTING2",
}

var Product_value = map[string]int32{
	"NO_PRODUCT":       0,
	"LIVE_DEBUGGING":   1,
	"APPSEC":           2,
	"RUNTIME_SECURITY": 3,
	"APM_SAMPLING":     4,
	"TESTING1":         5,
	"TESTING2":         6,
}

func (x Product) String() string {
	return proto.EnumName(Product_name, int32(x))
}

func (Product) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d3abb69cbc8aef5, []int{0}
}

type ClientLatestConfigsRequest struct {
	Hostname     string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AgentVersion string `protobuf:"bytes,2,opt,name=agentVersion,proto3" json:"agentVersion,omitempty"`
	// timestamp and snapshot versions move in tandem so they are the same.
	CurrentConfigSnapshotVersion uint64        `protobuf:"varint,3,opt,name=current_config_snapshot_version,json=currentConfigSnapshotVersion,proto3" json:"current_config_snapshot_version,omitempty"`
	CurrentConfigRootVersion     uint64        `protobuf:"varint,9,opt,name=current_config_root_version,json=currentConfigRootVersion,proto3" json:"current_config_root_version,omitempty"`
	CurrentDirectorRootVersion   uint64        `protobuf:"varint,8,opt,name=current_director_root_version,json=currentDirectorRootVersion,proto3" json:"current_director_root_version,omitempty"`
	Products                     []Product     `protobuf:"varint,4,rep,packed,name=products,proto3,enum=datadog.config.Product" json:"products,omitempty"`
	NewProducts                  []Product     `protobuf:"varint,5,rep,packed,name=new_products,json=newProducts,proto3,enum=datadog.config.Product" json:"new_products,omitempty"`
	ConnectedTracers             []*TracerInfo `protobuf:"bytes,6,rep,name=connected_tracers,json=connectedTracers,proto3" json:"connected_tracers,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}      `json:"-"`
	XXX_unrecognized             []byte        `json:"-"`
	XXX_sizecache                int32         `json:"-"`
}

func (m *ClientLatestConfigsRequest) Reset()         { *m = ClientLatestConfigsRequest{} }
func (m *ClientLatestConfigsRequest) String() string { return proto.CompactTextString(m) }
func (*ClientLatestConfigsRequest) ProtoMessage()    {}
func (*ClientLatestConfigsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3abb69cbc8aef5, []int{0}
}

func (m *ClientLatestConfigsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientLatestConfigsRequest.Unmarshal(m, b)
}
func (m *ClientLatestConfigsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientLatestConfigsRequest.Marshal(b, m, deterministic)
}
func (m *ClientLatestConfigsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientLatestConfigsRequest.Merge(m, src)
}
func (m *ClientLatestConfigsRequest) XXX_Size() int {
	return xxx_messageInfo_ClientLatestConfigsRequest.Size(m)
}
func (m *ClientLatestConfigsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientLatestConfigsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientLatestConfigsRequest proto.InternalMessageInfo

func (m *ClientLatestConfigsRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *ClientLatestConfigsRequest) GetAgentVersion() string {
	if m != nil {
		return m.AgentVersion
	}
	return ""
}

func (m *ClientLatestConfigsRequest) GetCurrentConfigSnapshotVersion() uint64 {
	if m != nil {
		return m.CurrentConfigSnapshotVersion
	}
	return 0
}

func (m *ClientLatestConfigsRequest) GetCurrentConfigRootVersion() uint64 {
	if m != nil {
		return m.CurrentConfigRootVersion
	}
	return 0
}

func (m *ClientLatestConfigsRequest) GetCurrentDirectorRootVersion() uint64 {
	if m != nil {
		return m.CurrentDirectorRootVersion
	}
	return 0
}

func (m *ClientLatestConfigsRequest) GetProducts() []Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *ClientLatestConfigsRequest) GetNewProducts() []Product {
	if m != nil {
		return m.NewProducts
	}
	return nil
}

func (m *ClientLatestConfigsRequest) GetConnectedTracers() []*TracerInfo {
	if m != nil {
		return m.ConnectedTracers
	}
	return nil
}

type LatestConfigsResponse struct {
	ConfigMetas          *ConfigMetas   `protobuf:"bytes,1,opt,name=config_metas,json=configMetas,proto3" json:"config_metas,omitempty"`
	DirectorMetas        *DirectorMetas `protobuf:"bytes,2,opt,name=director_metas,json=directorMetas,proto3" json:"director_metas,omitempty"`
	TargetFiles          []*File        `protobuf:"bytes,3,rep,name=target_files,json=targetFiles,proto3" json:"target_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LatestConfigsResponse) Reset()         { *m = LatestConfigsResponse{} }
func (m *LatestConfigsResponse) String() string { return proto.CompactTextString(m) }
func (*LatestConfigsResponse) ProtoMessage()    {}
func (*LatestConfigsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3abb69cbc8aef5, []int{1}
}

func (m *LatestConfigsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatestConfigsResponse.Unmarshal(m, b)
}
func (m *LatestConfigsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatestConfigsResponse.Marshal(b, m, deterministic)
}
func (m *LatestConfigsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestConfigsResponse.Merge(m, src)
}
func (m *LatestConfigsResponse) XXX_Size() int {
	return xxx_messageInfo_LatestConfigsResponse.Size(m)
}
func (m *LatestConfigsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestConfigsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LatestConfigsResponse proto.InternalMessageInfo

func (m *LatestConfigsResponse) GetConfigMetas() *ConfigMetas {
	if m != nil {
		return m.ConfigMetas
	}
	return nil
}

func (m *LatestConfigsResponse) GetDirectorMetas() *DirectorMetas {
	if m != nil {
		return m.DirectorMetas
	}
	return nil
}

func (m *LatestConfigsResponse) GetTargetFiles() []*File {
	if m != nil {
		return m.TargetFiles
	}
	return nil
}

type ConfigMetas struct {
	Roots                []*TopMeta       `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	Timestamp            *TopMeta         `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Snapshot             *TopMeta         `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	TopTargets           *TopMeta         `protobuf:"bytes,4,opt,name=topTargets,proto3" json:"topTargets,omitempty"`
	DelegatedTargets     []*DelegatedMeta `protobuf:"bytes,5,rep,name=delegatedTargets,proto3" json:"delegatedTargets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ConfigMetas) Reset()         { *m = ConfigMetas{} }
func (m *ConfigMetas) String() string { return proto.CompactTextString(m) }
func (*ConfigMetas) ProtoMessage()    {}
func (*ConfigMetas) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3abb69cbc8aef5, []int{2}
}

func (m *ConfigMetas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigMetas.Unmarshal(m, b)
}
func (m *ConfigMetas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigMetas.Marshal(b, m, deterministic)
}
func (m *ConfigMetas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigMetas.Merge(m, src)
}
func (m *ConfigMetas) XXX_Size() int {
	return xxx_messageInfo_ConfigMetas.Size(m)
}
func (m *ConfigMetas) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigMetas.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigMetas proto.InternalMessageInfo

func (m *ConfigMetas) GetRoots() []*TopMeta {
	if m != nil {
		return m.Roots
	}
	return nil
}

func (m *ConfigMetas) GetTimestamp() *TopMeta {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ConfigMetas) GetSnapshot() *TopMeta {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

func (m *ConfigMetas) GetTopTargets() *TopMeta {
	if m != nil {
		return m.TopTargets
	}
	return nil
}

func (m *ConfigMetas) GetDelegatedTargets() []*DelegatedMeta {
	if m != nil {
		return m.DelegatedTargets
	}
	return nil
}

type DirectorMetas struct {
	Roots                []*TopMeta `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	Timestamp            *TopMeta   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Snapshot             *TopMeta   `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Targets              *TopMeta   `protobuf:"bytes,4,opt,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DirectorMetas) Reset()         { *m = DirectorMetas{} }
func (m *DirectorMetas) String() string { return proto.CompactTextString(m) }
func (*DirectorMetas) ProtoMessage()    {}
func (*DirectorMetas) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3abb69cbc8aef5, []int{3}
}

func (m *DirectorMetas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectorMetas.Unmarshal(m, b)
}
func (m *DirectorMetas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectorMetas.Marshal(b, m, deterministic)
}
func (m *DirectorMetas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectorMetas.Merge(m, src)
}
func (m *DirectorMetas) XXX_Size() int {
	return xxx_messageInfo_DirectorMetas.Size(m)
}
func (m *DirectorMetas) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectorMetas.DiscardUnknown(m)
}

var xxx_messageInfo_DirectorMetas proto.InternalMessageInfo

func (m *DirectorMetas) GetRoots() []*TopMeta {
	if m != nil {
		return m.Roots
	}
	return nil
}

func (m *DirectorMetas) GetTimestamp() *TopMeta {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *DirectorMetas) GetSnapshot() *TopMeta {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

func (m *DirectorMetas) GetTargets() *TopMeta {
	if m != nil {
		return m.Targets
	}
	return nil
}

type DelegatedMeta struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Raw                  []byte   `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelegatedMeta) Reset()         { *m = DelegatedMeta{} }
func (m *DelegatedMeta) String() string { return proto.CompactTextString(m) }
func (*DelegatedMeta) ProtoMessage()    {}
func (*DelegatedMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3abb69cbc8aef5, []int{4}
}

func (m *DelegatedMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelegatedMeta.Unmarshal(m, b)
}
func (m *DelegatedMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelegatedMeta.Marshal(b, m, deterministic)
}
func (m *DelegatedMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegatedMeta.Merge(m, src)
}
func (m *DelegatedMeta) XXX_Size() int {
	return xxx_messageInfo_DelegatedMeta.Size(m)
}
func (m *DelegatedMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegatedMeta.DiscardUnknown(m)
}

var xxx_messageInfo_DelegatedMeta proto.InternalMessageInfo

func (m *DelegatedMeta) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DelegatedMeta) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *DelegatedMeta) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type TopMeta struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Raw                  []byte   `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopMeta) Reset()         { *m = TopMeta{} }
func (m *TopMeta) String() string { return proto.CompactTextString(m) }
func (*TopMeta) ProtoMessage()    {}
func (*TopMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3abb69cbc8aef5, []int{5}
}

func (m *TopMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopMeta.Unmarshal(m, b)
}
func (m *TopMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopMeta.Marshal(b, m, deterministic)
}
func (m *TopMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopMeta.Merge(m, src)
}
func (m *TopMeta) XXX_Size() int {
	return xxx_messageInfo_TopMeta.Size(m)
}
func (m *TopMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TopMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TopMeta proto.InternalMessageInfo

func (m *TopMeta) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TopMeta) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type File struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Raw                  []byte   `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3abb69cbc8aef5, []int{6}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type ConfigResponse struct {
	ConfigSnapshotVersion        uint64     `protobuf:"varint,1,opt,name=config_snapshot_version,json=configSnapshotVersion,proto3" json:"config_snapshot_version,omitempty"`
	ConfigDelegatedTargetVersion uint64     `protobuf:"varint,2,opt,name=config_delegated_target_version,json=configDelegatedTargetVersion,proto3" json:"config_delegated_target_version,omitempty"`
	DirectoryRoots               []*TopMeta `protobuf:"bytes,3,rep,name=directoryRoots,proto3" json:"directoryRoots,omitempty"`
	DirectoryTargets             *TopMeta   `protobuf:"bytes,4,opt,name=directoryTargets,proto3" json:"directoryTargets,omitempty"`
	TargetFiles                  []*File    `protobuf:"bytes,5,rep,name=target_files,json=targetFiles,proto3" json:"target_files,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}   `json:"-"`
	XXX_unrecognized             []byte     `json:"-"`
	XXX_sizecache                int32      `json:"-"`
}

func (m *ConfigResponse) Reset()         { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()    {}
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3abb69cbc8aef5, []int{7}
}

func (m *ConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResponse.Unmarshal(m, b)
}
func (m *ConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResponse.Marshal(b, m, deterministic)
}
func (m *ConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResponse.Merge(m, src)
}
func (m *ConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigResponse.Size(m)
}
func (m *ConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResponse proto.InternalMessageInfo

func (m *ConfigResponse) GetConfigSnapshotVersion() uint64 {
	if m != nil {
		return m.ConfigSnapshotVersion
	}
	return 0
}

func (m *ConfigResponse) GetConfigDelegatedTargetVersion() uint64 {
	if m != nil {
		return m.ConfigDelegatedTargetVersion
	}
	return 0
}

func (m *ConfigResponse) GetDirectoryRoots() []*TopMeta {
	if m != nil {
		return m.DirectoryRoots
	}
	return nil
}

func (m *ConfigResponse) GetDirectoryTargets() *TopMeta {
	if m != nil {
		return m.DirectoryTargets
	}
	return nil
}

func (m *ConfigResponse) GetTargetFiles() []*File {
	if m != nil {
		return m.TargetFiles
	}
	return nil
}

type SubscribeConfigRequest struct {
	CurrentConfigSnapshotVersion uint64      `protobuf:"varint,1,opt,name=current_config_snapshot_version,json=currentConfigSnapshotVersion,proto3" json:"current_config_snapshot_version,omitempty"`
	Product                      Product     `protobuf:"varint,2,opt,name=product,proto3,enum=datadog.config.Product" json:"product,omitempty"`
	TracerInfo                   *TracerInfo `protobuf:"bytes,3,opt,name=tracer_info,json=tracerInfo,proto3" json:"tracer_info,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}    `json:"-"`
	XXX_unrecognized             []byte      `json:"-"`
	XXX_sizecache                int32       `json:"-"`
}

func (m *SubscribeConfigRequest) Reset()         { *m = SubscribeConfigRequest{} }
func (m *SubscribeConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeConfigRequest) ProtoMessage()    {}
func (*SubscribeConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3abb69cbc8aef5, []int{8}
}

func (m *SubscribeConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeConfigRequest.Unmarshal(m, b)
}
func (m *SubscribeConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeConfigRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeConfigRequest.Merge(m, src)
}
func (m *SubscribeConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeConfigRequest.Size(m)
}
func (m *SubscribeConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeConfigRequest proto.InternalMessageInfo

func (m *SubscribeConfigRequest) GetCurrentConfigSnapshotVersion() uint64 {
	if m != nil {
		return m.CurrentConfigSnapshotVersion
	}
	return 0
}

func (m *SubscribeConfigRequest) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_NO_PRODUCT
}

func (m *SubscribeConfigRequest) GetTracerInfo() *TracerInfo {
	if m != nil {
		return m.TracerInfo
	}
	return nil
}

type GetConfigsRequest struct {
	Product                     Product     `protobuf:"varint,1,opt,name=product,proto3,enum=datadog.config.Product" json:"product,omitempty"`
	CurrentConfigProductVersion uint64      `protobuf:"varint,2,opt,name=current_config_product_version,json=currentConfigProductVersion,proto3" json:"current_config_product_version,omitempty"`
	CurrentDirectorRootVersion  uint64      `protobuf:"varint,3,opt,name=current_director_root_version,json=currentDirectorRootVersion,proto3" json:"current_director_root_version,omitempty"`
	TracerInfo                  *TracerInfo `protobuf:"bytes,4,opt,name=tracer_info,json=tracerInfo,proto3" json:"tracer_info,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}    `json:"-"`
	XXX_unrecognized            []byte      `json:"-"`
	XXX_sizecache               int32       `json:"-"`
}

func (m *GetConfigsRequest) Reset()         { *m = GetConfigsRequest{} }
func (m *GetConfigsRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigsRequest) ProtoMessage()    {}
func (*GetConfigsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3abb69cbc8aef5, []int{9}
}

func (m *GetConfigsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigsRequest.Unmarshal(m, b)
}
func (m *GetConfigsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigsRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigsRequest.Merge(m, src)
}
func (m *GetConfigsRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigsRequest.Size(m)
}
func (m *GetConfigsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigsRequest proto.InternalMessageInfo

func (m *GetConfigsRequest) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_NO_PRODUCT
}

func (m *GetConfigsRequest) GetCurrentConfigProductVersion() uint64 {
	if m != nil {
		return m.CurrentConfigProductVersion
	}
	return 0
}

func (m *GetConfigsRequest) GetCurrentDirectorRootVersion() uint64 {
	if m != nil {
		return m.CurrentDirectorRootVersion
	}
	return 0
}

func (m *GetConfigsRequest) GetTracerInfo() *TracerInfo {
	if m != nil {
		return m.TracerInfo
	}
	return nil
}

type GetConfigsResponse struct {
	ConfigResponses      []*ConfigResponse `protobuf:"bytes,1,rep,name=configResponses,proto3" json:"configResponses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetConfigsResponse) Reset()         { *m = GetConfigsResponse{} }
func (m *GetConfigsResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigsResponse) ProtoMessage()    {}
func (*GetConfigsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3abb69cbc8aef5, []int{10}
}

func (m *GetConfigsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigsResponse.Unmarshal(m, b)
}
func (m *GetConfigsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigsResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigsResponse.Merge(m, src)
}
func (m *GetConfigsResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigsResponse.Size(m)
}
func (m *GetConfigsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigsResponse proto.InternalMessageInfo

func (m *GetConfigsResponse) GetConfigResponses() []*ConfigResponse {
	if m != nil {
		return m.ConfigResponses
	}
	return nil
}

type TracerInfo struct {
	RuntimeId            string   `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	ServiceId            string   `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Env                  string   `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TracerInfo) Reset()         { *m = TracerInfo{} }
func (m *TracerInfo) String() string { return proto.CompactTextString(m) }
func (*TracerInfo) ProtoMessage()    {}
func (*TracerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3abb69cbc8aef5, []int{11}
}

func (m *TracerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TracerInfo.Unmarshal(m, b)
}
func (m *TracerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TracerInfo.Marshal(b, m, deterministic)
}
func (m *TracerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TracerInfo.Merge(m, src)
}
func (m *TracerInfo) XXX_Size() int {
	return xxx_messageInfo_TracerInfo.Size(m)
}
func (m *TracerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TracerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TracerInfo proto.InternalMessageInfo

func (m *TracerInfo) GetRuntimeId() string {
	if m != nil {
		return m.RuntimeId
	}
	return ""
}

func (m *TracerInfo) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *TracerInfo) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

func (m *TracerInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterEnum("datadog.config.Product", Product_name, Product_value)
	proto.RegisterType((*ClientLatestConfigsRequest)(nil), "datadog.config.ClientLatestConfigsRequest")
	proto.RegisterType((*LatestConfigsResponse)(nil), "datadog.config.LatestConfigsResponse")
	proto.RegisterType((*ConfigMetas)(nil), "datadog.config.ConfigMetas")
	proto.RegisterType((*DirectorMetas)(nil), "datadog.config.DirectorMetas")
	proto.RegisterType((*DelegatedMeta)(nil), "datadog.config.DelegatedMeta")
	proto.RegisterType((*TopMeta)(nil), "datadog.config.TopMeta")
	proto.RegisterType((*File)(nil), "datadog.config.File")
	proto.RegisterType((*ConfigResponse)(nil), "datadog.config.ConfigResponse")
	proto.RegisterType((*SubscribeConfigRequest)(nil), "datadog.config.SubscribeConfigRequest")
	proto.RegisterType((*GetConfigsRequest)(nil), "datadog.config.GetConfigsRequest")
	proto.RegisterType((*GetConfigsResponse)(nil), "datadog.config.GetConfigsResponse")
	proto.RegisterType((*TracerInfo)(nil), "datadog.config.TracerInfo")
}

func init() { proto.RegisterFile("datadog/config/config.proto", fileDescriptor_5d3abb69cbc8aef5) }

var fileDescriptor_5d3abb69cbc8aef5 = []byte{
	// 921 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc6, 0x71, 0xd2, 0x34, 0x27, 0x69, 0xf0, 0x8e, 0x76, 0xd9, 0xa8, 0xa5, 0x4b, 0xe5, 0xab,
	0x0a, 0x41, 0xab, 0x76, 0xb5, 0xac, 0x04, 0x02, 0xd4, 0x4d, 0x42, 0xb0, 0xd4, 0x9f, 0xc8, 0x71,
	0x57, 0x82, 0x0b, 0x2c, 0xd7, 0x9e, 0xa6, 0x16, 0xa9, 0xc7, 0xcc, 0x4c, 0x52, 0x71, 0xc1, 0x13,
	0xf0, 0x2a, 0x3c, 0x0b, 0xdc, 0x71, 0x87, 0x78, 0x15, 0x34, 0xe3, 0x19, 0xc7, 0x76, 0xba, 0x21,
	0xdc, 0x71, 0x95, 0x99, 0x33, 0xdf, 0xf7, 0xcd, 0xf8, 0xcc, 0x39, 0xdf, 0x04, 0xf6, 0xa2, 0x80,
	0x07, 0x11, 0x99, 0x1e, 0x87, 0x24, 0xb9, 0x8d, 0xf5, 0xcf, 0x51, 0x4a, 0x09, 0x27, 0xa8, 0xab,
	0x16, 0x8f, 0xb2, 0xa8, 0xfd, 0xb7, 0x09, 0xbb, 0xfd, 0x59, 0x8c, 0x13, 0x7e, 0x1e, 0x70, 0xcc,
	0x78, 0x5f, 0x86, 0x99, 0x8b, 0x7f, 0x9a, 0x63, 0xc6, 0xd1, 0x2e, 0x6c, 0xdf, 0x11, 0xc6, 0x93,
	0xe0, 0x1e, 0xf7, 0x8c, 0x03, 0xe3, 0xb0, 0xe5, 0xe6, 0x73, 0x64, 0x43, 0x27, 0x98, 0xe2, 0x84,
	0xbf, 0xc5, 0x94, 0xc5, 0x24, 0xe9, 0xd5, 0xe4, 0x7a, 0x29, 0x86, 0x86, 0xf0, 0x51, 0x38, 0xa7,
	0x14, 0x27, 0xdc, 0xcf, 0x36, 0xf4, 0x59, 0x12, 0xa4, 0xec, 0x8e, 0x70, 0x7f, 0xa1, 0x68, 0xe6,
	0x81, 0x71, 0x58, 0x77, 0x3f, 0x54, 0xb0, 0x6c, 0xff, 0x89, 0x02, 0x69, 0x99, 0x2f, 0x61, 0xaf,
	0x22, 0x43, 0x49, 0x41, 0xa2, 0x25, 0x25, 0x7a, 0x25, 0x09, 0x97, 0x2c, 0xe9, 0x67, 0xb0, 0xaf,
	0xe9, 0x51, 0x4c, 0x71, 0xc8, 0x09, 0x2d, 0x0b, 0x6c, 0x4b, 0x81, 0x5d, 0x05, 0x1a, 0x28, 0x4c,
	0x51, 0xe2, 0x25, 0x6c, 0xa7, 0x94, 0x44, 0xf3, 0x90, 0xb3, 0x5e, 0xfd, 0xc0, 0x3c, 0xec, 0x9e,
	0x3e, 0x3f, 0x2a, 0xa7, 0xf2, 0x68, 0x9c, 0xad, 0xbb, 0x39, 0x10, 0x7d, 0x0e, 0x9d, 0x04, 0x3f,
	0xf8, 0x39, 0xb1, 0xb1, 0x9e, 0xd8, 0x4e, 0xf0, 0xc3, 0x58, 0x73, 0x47, 0xf0, 0x24, 0x24, 0x49,
	0x82, 0x43, 0x8e, 0x23, 0x9f, 0xd3, 0x20, 0xc4, 0x94, 0xf5, 0xb6, 0x0e, 0xcc, 0xc3, 0xf6, 0xe9,
	0x6e, 0x55, 0xc0, 0x93, 0xcb, 0x4e, 0x72, 0x4b, 0x5c, 0x2b, 0x27, 0x65, 0x41, 0x66, 0xff, 0x69,
	0xc0, 0xb3, 0xca, 0xdd, 0xb2, 0x94, 0x24, 0x0c, 0xa3, 0xaf, 0xa0, 0xa3, 0xb2, 0x79, 0x8f, 0x79,
	0xc0, 0xe4, 0x05, 0xb7, 0x4f, 0xf7, 0xaa, 0xea, 0x19, 0xed, 0x42, 0x40, 0xdc, 0x76, 0xb8, 0x9c,
	0xa0, 0x01, 0x74, 0xf3, 0x74, 0x66, 0x0a, 0x35, 0xa9, 0xb0, 0x5f, 0x55, 0xd0, 0x09, 0xcd, 0x34,
	0x76, 0xa2, 0xe2, 0x14, 0xbd, 0x86, 0x0e, 0x0f, 0xe8, 0x14, 0x73, 0xff, 0x36, 0x9e, 0x61, 0xd6,
	0x33, 0xe5, 0x37, 0x3e, 0xad, 0x6a, 0x7c, 0x13, 0xcf, 0xb0, 0xdb, 0xce, 0x90, 0x62, 0xcc, 0xec,
	0xdf, 0x6a, 0xd0, 0x2e, 0x9c, 0x0d, 0x7d, 0x0a, 0x0d, 0x71, 0xa9, 0xe2, 0x3b, 0x84, 0xc2, 0x4a,
	0x9a, 0x3d, 0x92, 0x0a, 0xa0, 0x9b, 0xa1, 0xd0, 0x2b, 0x68, 0xf1, 0xf8, 0x1e, 0x33, 0x1e, 0xdc,
	0xa7, 0xea, 0xe0, 0xef, 0xa4, 0x2c, 0x91, 0xa2, 0x10, 0x74, 0x09, 0xcb, 0xd2, 0x5d, 0xc3, 0xca,
	0x81, 0xe8, 0x35, 0x00, 0x27, 0xa9, 0x27, 0x0f, 0x2f, 0xea, 0x67, 0x2d, 0xad, 0x00, 0x45, 0x0e,
	0x58, 0x11, 0x9e, 0xe1, 0x69, 0x20, 0x2e, 0x54, 0xd1, 0x1b, 0xf2, 0xf3, 0x56, 0x93, 0xac, 0x71,
	0x52, 0x64, 0x85, 0x66, 0xff, 0x65, 0xc0, 0x4e, 0xe9, 0x22, 0xfe, 0xcf, 0x09, 0x3b, 0x81, 0x26,
	0xdf, 0x2c, 0x5b, 0x1a, 0x67, 0x5f, 0xc1, 0x4e, 0x29, 0x05, 0xa8, 0x07, 0x4d, 0xdd, 0xdf, 0x86,
	0xec, 0x6f, 0x3d, 0x45, 0x08, 0xea, 0x94, 0xcc, 0xb0, 0x72, 0x2c, 0x39, 0x46, 0x16, 0x98, 0x34,
	0x78, 0x90, 0x27, 0xec, 0xb8, 0x62, 0x68, 0xbf, 0x82, 0xa6, 0xda, 0x64, 0x8d, 0x94, 0xa2, 0xd5,
	0x96, 0xb4, 0x4f, 0xa0, 0x2e, 0xea, 0x53, 0x6c, 0x92, 0x06, 0xfc, 0x4e, 0xd9, 0xa6, 0x1c, 0x3f,
	0x82, 0xfe, 0xbd, 0x06, 0x5d, 0x65, 0x58, 0xba, 0x2d, 0x3f, 0x83, 0xe7, 0xef, 0xf2, 0xca, 0x6c,
	0xf3, 0x67, 0xe1, 0xa3, 0x26, 0x29, 0xbc, 0x36, 0xe3, 0xe5, 0x77, 0xef, 0xab, 0xce, 0x5a, 0x14,
	0x2c, 0x5a, 0x78, 0xad, 0x84, 0x0d, 0xca, 0x15, 0xa2, 0x65, 0xbe, 0x5e, 0x76, 0xf5, 0xcf, 0xae,
	0x2c, 0x0f, 0x73, 0x7d, 0x79, 0x54, 0xe0, 0xa8, 0x0f, 0x56, 0x1e, 0xd9, 0xb0, 0xe4, 0x57, 0x08,
	0x2b, 0xae, 0xd0, 0xd8, 0xd4, 0x15, 0xfe, 0x30, 0xe0, 0x83, 0xc9, 0xfc, 0x86, 0x85, 0x34, 0xbe,
	0xc1, 0x3a, 0xb3, 0xd9, 0x63, 0xb6, 0xc1, 0x63, 0x64, 0x6c, 0xf0, 0x18, 0x9d, 0x40, 0x53, 0x39,
	0xba, 0xcc, 0xe7, 0x1a, 0x43, 0xd7, 0x38, 0xf4, 0x05, 0xb4, 0x33, 0x0b, 0xf7, 0xe3, 0xe4, 0x96,
	0xa8, 0x36, 0x58, 0x67, 0xe3, 0xc0, 0xf3, 0xb1, 0xfd, 0x6b, 0x0d, 0x9e, 0x8c, 0x70, 0xf5, 0x65,
	0x2e, 0x9c, 0xc2, 0xd8, 0xf0, 0x14, 0x7d, 0x78, 0x51, 0xf9, 0x7e, 0xb5, 0x52, 0xa9, 0x8f, 0xbd,
	0xd2, 0xe7, 0x2b, 0x99, 0x8d, 0xdf, 0x52, 0xf3, 0x5f, 0xdf, 0xd2, 0x4a, 0x36, 0xea, 0xff, 0x29,
	0x1b, 0x3f, 0x00, 0x2a, 0x26, 0x43, 0xf5, 0xcc, 0xb7, 0xf0, 0x7e, 0x58, 0xea, 0x22, 0x6d, 0x6a,
	0x2f, 0x1e, 0x7f, 0xcd, 0x34, 0xcc, 0xad, 0xd2, 0xec, 0x05, 0xc0, 0x72, 0x67, 0xb4, 0x0f, 0x40,
	0xe7, 0x89, 0x30, 0x33, 0x3f, 0x8e, 0x54, 0x2b, 0xb7, 0x54, 0xc4, 0x89, 0xc4, 0x32, 0xc3, 0x74,
	0x11, 0x87, 0x72, 0x39, 0xb3, 0x93, 0x96, 0x8a, 0x38, 0x91, 0x68, 0x77, 0x9c, 0x2c, 0x64, 0x46,
	0x5a, 0xae, 0x18, 0x16, 0x8d, 0xa4, 0x2e, 0xa3, 0x7a, 0xfa, 0xf1, 0x2f, 0xd0, 0x54, 0x99, 0x46,
	0x5d, 0x80, 0xcb, 0x2b, 0x7f, 0xec, 0x5e, 0x0d, 0xae, 0xfb, 0x9e, 0xf5, 0x1e, 0x42, 0xd0, 0x3d,
	0x77, 0xde, 0x0e, 0xfd, 0xc1, 0xf0, 0xcd, 0xf5, 0x68, 0xe4, 0x5c, 0x8e, 0x2c, 0x03, 0x01, 0x6c,
	0x9d, 0x8d, 0xc7, 0x93, 0x61, 0xdf, 0xaa, 0xa1, 0xa7, 0x60, 0xb9, 0xd7, 0x97, 0x9e, 0x73, 0x31,
	0xf4, 0x27, 0xc3, 0xfe, 0xb5, 0xeb, 0x78, 0xdf, 0x59, 0x26, 0xb2, 0xa0, 0x73, 0x36, 0xbe, 0xf0,
	0x27, 0x67, 0x17, 0xe3, 0x73, 0xc1, 0xa9, 0xa3, 0x0e, 0x6c, 0x7b, 0xc3, 0x89, 0xe7, 0x5c, 0x8e,
	0x4e, 0xac, 0x46, 0x61, 0x76, 0x6a, 0x6d, 0xbd, 0xb1, 0xbe, 0xef, 0xa6, 0x3f, 0x4e, 0x8f, 0xe5,
	0x9f, 0xc4, 0xe3, 0xf4, 0x66, 0x4a, 0x6e, 0xb6, 0xe4, 0xf8, 0xe5, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x21, 0xea, 0x3f, 0x3e, 0x4f, 0x0a, 0x00, 0x00,
}
